# Generated by Django 6.0.5 on 2026-05-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('client', 'client'), ('employee', 'employee')], max_length=20)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_surface_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ceiling_surface_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_windows', models.IntegerField(default=0)),
                ('number_of_doors', models.IntegerField(default=0)),
                ('selected_additional_services', models.JSONField(default=list)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_updated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inquiry_status', models.CharField(choices=[('new', 'new'), ('estimated', 'estimated'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=50)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimations.inquiry')),
            ],
        ),
    ]
