# Generated by Django 6.0.5 on 2026-05-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='estimations.inquiry'),
        ),
    ]
