# Generated by Django 6.0.5 on 2026-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0002_alter_estimation_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
